---

- name: Checking curl installation
  become: yes
  apt:
    name: curl
    state: present

- name: Checking the latest version
  become: yes
  shell: 'curl -s https://api.github.com/repos/opensbom-generator/spdx-sbom-generator/releases/latest | grep "browser_download_url.*linux-amd64.tar.gz" | cut -d : -f 2,3 | tr -d \" | head -1 | xargs'
  register: latest_version

- name: Download and Extract spdx-generator tool
  become: yes
  unarchive:
    src: "{{ latest_version.stdout }}"
    dest: /opt/
    remote_src: yes
