- name: Check if spdx-sbom-generator file exists
  stat:
    path: "{{ spdx_sbom_path }}/spdx-sbom-generator"
  register: sbom_file

- name: Display file existence status
  debug:
    msg: "spdx-sbom-generator file exists: {{ sbom_file.stat.exists }}"

- name: Exit if file exists
  fail:
    msg: "spdx-sbom-generator file already exists. Exiting role execution."
  when: sbom_file.stat.exists

- name: Checking curl installation
  become: yes
  apt:
    name: curl
    state: present

- name: Download and Extract spdx-generator tool
  become: yes
  unarchive:
    src: "{{ spdx_sbom_download_url }}/{{ spdx_sbom_version }}/spdx-sbom-generator-{{ spdx_sbom_version }}-linux-amd64.tar.gz"
    dest: "{{ spdx_sbom_path }}"
    remote_src: yes