- name: Validate Installation
  stat:
    path: "{{ spdx_sbom_path }}"
  register: spdx_executable

- name: Display file existence status
  debug:
    msg: "spdx-sbom-generator is not installed"
  when: not sbom_file.stat.exists

- name: End execution of role
  meta: end_role
  when: not spdx_executable.stat.exists

- name: Spdx-generator installed
  debug:
    msg: sbom-spdx-generator is installed
  when: spdx_executable.stat.exists